spring:
  application:
    name: mini_spring
  profiles:
    active: local # 기본 실행 환경 (로컬)

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false


jwt:
  access-token-expiration: 3600000  # 1시간
  refresh-token-expiration: 604800000 # 7일

springdoc:
  querydsl:
    enabled: false
  swagger-ui:
    defaultModelsExpandDepth: -1
    defaultModelExpandDepth: 0
    displayRequestDuration: true